---
- name: install Apache
  yum:
    name: httpd
    state: latest

- name: configure Apache
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^DirectoryIndex'
    insertbefore: '^index.html'
    line: index.php

- name: clone the tooling website from GitHub
  git: 
    repo: https://github.com/chauntelkellar/tooling.git
    dest: /tmp/tooling
  
- name: copying /tmp/tooling/html folder contents to /var/www/html
  copy:
    src: /tmp/tooling/html
    dest: /var/www
    owner: apache
    group: apache
    mode: '0770'
    remote_src: yes

      
